stages:
  - bump_version
  - release
  - release_notify

variables:
  TRELLIS_GIT_POST: https://trellis.getto.systems/git/post/1.5.2
  TRELLIS_CI_BUMP_VERSION: https://trellis.getto.systems/ci/bump-version/1.10.2
  TRELLIS_PSYCHER_GETTO: https://trellis.getto.systems/psycher/getto/2.7.2

bump_version:
  stage: bump_version
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:buster-scm

  before_script:
    - git config user.email shun.fix9@gmail.com
    - git config user.name shun
    - curl $TRELLIS_GIT_POST/setup.sh | sh -s -- ./vendor/getto-systems
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
  script:
    - curl $TRELLIS_CI_BUMP_VERSION/bump_version.sh | bash
    - curl $TRELLIS_CI_BUMP_VERSION/request.sh | bash -s -- ./.bump-message.sh

release:
  stage: release
  only:
    refs:
      - release@shun-fix9-base/labo/qwerty
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules

  image: buildpack-deps:buster-scm

  script:
    - curl $TRELLIS_CI_BUMP_VERSION/push_tags.sh | sh

release_success:
  stage: release_notify
  only:
    refs:
      - release@shun-fix9-base/labo/qwerty
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=blog:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-success.sh | sh -s -- $url $channel $version

release_failure:
  stage: release_notify
  only:
    refs:
      - release@shun-fix9-base/labo/qwerty
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_failure

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=blog:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-failure.sh | sh -s -- $url $channel $version
